# This file contains the configuration for the "Email Copilot" tutorial.
#
# Learn more: https://www.tensorzero.com/docs/gateway/tutorial/

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                   MODELS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[models.my_gpt_4o_mini]
routing = ["my_openai_provider"]

[models.my_gpt_4o_mini.providers.my_openai_provider]
type = "openai"
model_name = "gpt-4o-mini-2024-07-18"

[models.my_gpt_4o]
routing = ["my_openai_provider_4o"]

[models.my_gpt_4o.providers.my_openai_provider_4o]
type = "openai"
model_name = "gpt-4o-2024-05-13"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.draft_email]
type = "chat"
user_schema = "functions/draft_email/user_schema.json"

[functions.draft_email.variants.gpt_4o_mini_email_variant]
type = "chat_completion"
weight = 0.7 # sample this variant 70% of the time
model = "my_gpt_4o_mini"
system_template = "functions/draft_email/gpt_4o_mini_email_variant/system.minijinja"
user_template = "functions/draft_email/gpt_4o_mini_email_variant/user.minijinja"

[functions.draft_email.variants.gpt_4o_email_variant]
type = "chat_completion"
weight = 0.3 # sample this variant 30% of the time
model = "my_gpt_4o"
system_template = "functions/draft_email/haiku_3_email_variant/system.minijinja"
user_template = "functions/draft_email/haiku_3_email_variant/user.minijinja"
temperature = 0.9

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  METRICS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[metrics.email_draft_accepted]
type = "boolean"
optimize = "max"
level = "inference"